### ISSUE TITLE
Type Definition file?

### ISSUE THREAD

**Issue by P0oOOOo0YA** [terasum/js-mdict#2]
Hi, i need to use some `.mdx` dictionary files in a typescript project. Do you plan to provide a type definition file for your library?

**Comment by terasum** [comment]
yes, of course, but currently, my main efforts enhance the performance of js-mdict, so maybe later, I will provide a type definition file. I will add this into my todo list.

**Comment by terasum** [comment]
@P0oOOOo0YA hi, I'm sorry for this late, but I have updated js-mdict library for version 4.0.5, it includes a type definition file in `typings` directory, and the dictionary file load speed has enhanced (less than 0.5 second), but some api has changed. please check this.
