### ISSUE TITLE
类型声明与实现不一致

### ISSUE THREAD

**Issue by songxiaocheng** [terasum/js-mdict#29]
1. mdict.d.ts 中，`class Mdict` 的方法全都返回的值，然而实现中 `suggest` 方法返回的却是 `Promise`
2. mdict.d.ts 中，`prefix`、`fuzzy_search` 和 `associate` 方法均返回 `Array<WordIndex>`，`WordIndex`声明如下：https://github.com/terasum/js-mdict/blob/a3f75312071d0433ff808f994ce4f7fbf292ad03/typings/mdict.d.ts#L76-L80
然而，`prefix` 和 `fuzzy_search` 实际返回的元素属性为 `key` 和 `rofset`，`associate` 实际返回的为 `keyText` 和 `recordStartOffset`，均与类型声明不一致。

**Comment by terasum** [comment]
@songxiaocheng typings 的问题我这两天正在改，你说的这几个问题我优先修复

**Comment by terasum** [comment]
已经修复 #32

**Comment by terasum** [comment]
在版本 v4.0.12 中修复了上面提及的类型声明问题

**Comment by songxiaocheng** [comment]
@terasum 这个问题似乎并没有改变，您再检查一下？

您在 `WordIndex` 中加了一个 `recordStartOffset` 属性，我不太清楚这和 `roffset` 是否是一回事，但是看起来同时出现的时候值都是相同的。

现在类型声明是这样的：
https://github.com/terasum/js-mdict/blob/0852fe63400869f17f0899377a3839597b86bc7d/typings/mdict.d.ts#L86-L89
https://github.com/terasum/js-mdict/blob/0852fe63400869f17f0899377a3839597b86bc7d/typings/mdict.d.ts#L76-L81
而跑示例代码各函数返回结果输出如下：
`prefix`:
```
[
  { key: 'he', rofset: 159249487 },
  ...
]
```
`fuzzy_search`:
```
[
  { keyText: 'Hf', roffset: 162785938, ed: 5 },
  ...
]
```
`associate`:
```
[
  { recordStartOffset: 239812169, keyText: 'on', rofset: 239812169 },
  ...
]
```
其中这些条目的 `recordStartOffset` 和 `rofset` 都是相同的值。

**Comment by terasum** [comment]
我重新看了一下这部分的代码，应该是全部都统一为 `rofset` 这个名称，这个名称是特意命名成这样的，意思就是 `recordStartOffset`， 在 `associate` 中为了向前兼容，保留了两个命名

**Comment by terasum** [comment]
fuzzy_search 返回的应该也是 `roffset` 的:
https://github.com/terasum/js-mdict/blob/f44d84f9f4c6d58ebd13168d6f3bed25c5affebd/src/mdict.js#L205
