### ISSUE TITLE
`fuzzy_search` 函数签名与实现不一致

### ISSUE THREAD

**Issue by songxiaocheng** [terasum/js-mdict#30]
虽然发现以前解决过这个问题（#4），不过现在我用了五个词典测试，都返回为空，用了 README 里面示例的单词”hitch“，也试了其它单词，全部返回为空数组。

**Comment by terasum** [comment]
`fuzzy_search` 这个函数我本地的测试是可以通过的，可以看看你的使用时候的代码是怎么写的吗？

**Comment by songxiaocheng** [comment]
@terasum 抱歉，我知道怎么回事了，因为我用的 typescript，尝试示例报错，看了类型声明之后我以为是示例没有更新，我就把后两个参数删掉了，后来忘了这回事。应该只需要改一下这条类型声明就可
https://github.com/terasum/js-mdict/blob/0852fe63400869f17f0899377a3839597b86bc7d/typings/mdict.d.ts#L88
