### ISSUE TITLE
Switch to a newer version of xmldom

### ISSUE THREAD

**Issue by Sam0230** [terasum/js-mdict#64]
See https://github.com/advisories/GHSA-5fg8-2547-mr8q and https://github.com/xmldom/xmldom/discussions/270.

**Comment by Sam0230** [comment]
xmldom 0.6.0 is vulnerable to maliciously elaborated document, and the new versions are published to npm as @xmldom/xmldom.

**Comment by terasum** [comment]
thanks to report, I'll fix this
