### ISSUE TITLE
Mduce 不是构造函数，请问一下，我这里哪里搞错了？

### ISSUE THREAD

**Issue by iibrat** [terasum/js-mdict#81]
![image](https://github.com/user-attachments/assets/885920fb-fee1-4937-bfe5-7a804a52582f)
Mdict is not a constructor

我是在 electron 的主进程中测试的

**Comment by terasum** [comment]
我理解应该是打包代码的方式的问题，你看看这个 https://github.com/terasum/medict/blob/afe81bc74d3219449150b66b5efd2aa35227dc7c/src/infra/Dictionary.ts#L82

**Comment by terasum** [comment]
如果是electron 你可以参考这个项目 https://github.com/terasum/medict/blob/v2-stable/src/infra/Dictionary.ts#L82

**Comment by iibrat** [comment]
> 我理解应该是打包代码的方式的问题，你看看这个 https://github.com/terasum/medict/blob/afe81bc74d3219449150b66b5efd2aa35227dc7c/src/infra/Dictionary.ts#L82

我看了也是一样的用法，导入  然后 new Mdict 。
我这个 electron-vite 建的项目，可以跟这个有关。

**Comment by terasum** [comment]
或者你先试试用es5 require的方式先试试，我下午修复一下

| |
ChenQuan
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月27日 12:16 |
| 收件人 | terasum/js-mdict ***@***.***> |
| 抄送人 | Quan ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [terasum/js-mdict] Mduce 不是构造函数，请问一下，我这里哪里搞错了？ (Issue #81) |

我理解应该是打包代码的方式的问题，你看看这个 https://github.com/terasum/medict/blob/afe81bc74d3219449150b66b5efd2aa35227dc7c/src/infra/Dictionary.ts#L82

我看了也是一样的用法，导入 然后 new Mdict 。
我这个 electron-vite 建的项目，可以跟这个有关。

**Comment by iibrat** [comment]
或者你先试试用es5 require的方式先试试，我下午修复一下

我也是一样学一边开发！！
要是你愿意修复，那太感谢了，我晚上再来试试。

**Comment by iibrat** [comment]
我好像还是原来的问题，请问一下，要怎么获取你修复后的版本？

**Comment by terasum** [comment]
我代码改好了还在测试，稍微晚点我推到npm仓库

| |
ChenQuan
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月28日 12:08 |
| 收件人 | terasum/js-mdict ***@***.***> |
| 抄送人 | Quan ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [terasum/js-mdict] Mduce 不是构造函数，请问一下，我这里哪里搞错了？ (Issue #81) |

我好像还是原来的问题，请问一下，要怎么获取你修复后的版本？

**Comment by iibrat** [comment]
> 我代码改好了还在测试，稍微晚点我推到npm仓库 | | ChenQuan | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年09月28日 12:08 | | 收件人 | terasum/js-mdict ***@***.***> | | 抄送人 | Quan ***@***.***>, Comment ***@***.***> | | 主题 | Re: [terasum/js-mdict] Mduce 不是构造函数，请问一下，我这里哪里搞错了？ (Issue #81) | 我好像还是原来的问题，请问一下，要怎么获取你修复后的版本？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

好的，谢了！！！

**Comment by terasum** [comment]
将 package.json 中的 js-mdcit的版本修改为 5.0.5，再试试这个代码，
```
import { assert } from "chai";
import { Mdict } from "js-mdict";
console.log(Mdict);

const mdict = new Mdict("resources/oald7.mdx", {
  resort: true,
});

const matched = mdict.associate("on");
assert.isTrue(matched.length > 0);
assert.isTrue(matched != undefined);
assert.isTrue(matched[0] != undefined);

let defination = mdict.fetch_defination(matched[0]);

assert.isTrue(
  defination.definition.startsWith(
    `<head><link rel=\"stylesheet\" type=\"text/css\" href=\"O7.css\"/>`
  )
);

const def = mdict.lookup("ask");
console.log(def.definition)
assert.isNotEmpty(def.definition);
assert.equal(
  def.keyText,
  "ask",
  "definition result should be equal with `ask`"
);

```

**Comment by iibrat** [comment]
> 将 package.json 中的 js-mdcit的版本修改为 5.0.5，再试试这个代码，
> 
> ```
> import { assert } from "chai";
> import { Mdict } from "js-mdict";
> console.log(Mdict);
> 
> const mdict = new Mdict("resources/oald7.mdx", {
>   resort: true,
> });
> 
> const matched = mdict.associate("on");
> assert.isTrue(matched.length > 0);
> assert.isTrue(matched != undefined);
> assert.isTrue(matched[0] != undefined);
> 
> let defination = mdict.fetch_defination(matched[0]);
> 
> assert.isTrue(
>   defination.definition.startsWith(
>     `<head><link rel=\"stylesheet\" type=\"text/css\" href=\"O7.css\"/>`
>   )
> );
> 
> const def = mdict.lookup("ask");
> console.log(def.definition)
> assert.isNotEmpty(def.definition);
> assert.equal(
>   def.keyText,
>   "ask",
>   "definition result should be equal with `ask`"
> );
> ```

好的，我明天试一下。

**Comment by terasum** [comment]
@iibrat 你好，我重写了整个库，发布了 `6.0.0-alpha-1` 版本，你可以试试这个版本。
安装方式:

```
npm install js-mdict@ 6.0.0-alpha-1 
```

示例代码：
文件名: demo.mjs
```javascript
import { assert } from "chai";
import { Mdict } from "js-mdict";

const mdict = new Mdict("resources/oald7.mdx", {
  resort: true,
});

const def = mdict.lookup("ask");
console.log(def.definition);
assert.isNotEmpty(def.definition);
assert.equal(
  def.keyText,
  "ask",
  "definition result should be equal with `ask`"
);

```
测试命令；

```
node demo.mjs
```

**Comment by iibrat** [comment]
@terasum 好的，我本来想用这个把 牛津高阶英语词典导入到软件中，用来查单词，但我现在边学边开发的情况下，难度不挺大的，我现在直接用AI去查单词，挺方便的，用有道的api做单词发音，能凑合着用。我试试你的新版本，如果能用的话我就换回来，毕竟牛津词典的解释还是很详细的。

**Comment by terasum** [comment]
@iibrat 可以的，如果你是这个需求，可以看看 https://github.com/terasum/medict 这个软件，应该实现了你的需求。
